apiVersion: v1
kind: Service
metadata:
  name: etcdcluster
  namespace: default
spec:
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  selector:
    component: etcdcluster-sample