apiVersion: db.imind.tech/v1beta1
kind: EtcdCluster
metadata:
  labels:
    app.kubernetes.io/name: etcdcluster
    app.kubernetes.io/instance: etcdcluster-sample
    app.kubernetes.io/part-of: etcd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: etcd-operator
  name: etcdcluster-sample
spec:
  image: quay.io/coreos/etcd:v3.5.5-amd64
  size: 3

